### ISSUE TITLE
live example not working?

### ISSUE THREAD

**Issue by prioritylabs** [wellcometrust/timeline#7]
timeline not working
 https://wellcomelibrary.org/collections/digital-collections/makers-of-modern-genetics/genetics-timeline/
shows empty page (only header and footer of the page)

**Comment by tomcrane** [comment]
Hi @prioritylabs 
Thanks for the info. The problem is here - https://github.com/wellcometrust/timeline/blob/master/src/js/embed.js#L153

Need to consider protocol as well as other link props. 

It works over http: 
http://wellcomelibrary.org/collections/digital-collections/makers-of-modern-genetics/genetics-timeline/

I will fix this. Thanks!

**Comment by tomcrane** [comment]
Hi @jennpb - seeing as this is now a wellcometrust repo, I didn't accept my own pull request (https://github.com/wellcometrust/timeline/pull/8). I have deployed the fix to wellcomelibrary.org though, as https://github.com/wellcomelibrary/dds-ecosystem/pull/23.

**Comment by tomcrane** [comment]
@edsilv FYI - fixed in #8
